#!/bin/bash
echo "=============================================="
echo "     OPEN SOURCE MANIFESTO GENERATOR         "
echo "=============================================="
echo ""
echo "  Answer three questions to generate"
echo "  your personal open source manifesto."
echo ""
read -p "  1. Name one open-source tool you use every day: " TOOL
echo ""
read -p "  2. In one word, what does 'freedom' mean to you? " FREEDOM
echo ""
read -p "  3. Name one thing you would build and share freely: " BUILD
echo ""
DATE=$(date '+%d %B %Y')
AUTHOR=$(whoami)
OUTPUT="manifesto_${AUTHOR}.txt"
echo "----------------------------------------------"
echo "  Generating your manifesto..."
echo "----------------------------------------------"
echo ""
echo "==============================================" > "$OUTPUT"
echo "       MY OPEN SOURCE MANIFESTO              " >> "$OUTPUT"
echo "==============================================" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "  Author : $AUTHOR" >> "$OUTPUT"
echo "  Date   : $DATE" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "----------------------------------------------" >> "$OUTPUT"
echo "  Every day, I rely on $TOOL -- a tool that someone" >> "$OUTPUT"
echo "  built, shared, and gave to the world without asking" >> "$OUTPUT"
echo "  for anything in return. That act of sharing is what" >> "$OUTPUT"
echo "  open source means to me: it means $FREEDOM." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "  I believe that knowledge grows when it is shared," >> "$OUTPUT"
echo "  not hoarded. The best software in the world was" >> "$OUTPUT"
echo "  built openly, collaboratively, and freely." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "  One day, I want to build $BUILD and release it" >> "$OUTPUT"
echo "  as open source -- so that someone I will never meet" >> "$OUTPUT"
echo "  can use it, improve it, and pass it forward." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "  That is the open source way." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "  -- $AUTHOR, $DATE" >> "$OUTPUT"
echo "==============================================" >> "$OUTPUT"
echo "  Manifesto saved to: $OUTPUT"
echo ""
echo "----------------------------------------------"
cat "$OUTPUT"
echo ""
echo "=============================================="
